In [2]:
import statistics as st

In [4]:
a = [20,10,50,10,21,19]
s = st.mode(a)
print("Mode : ",s)
m = st.mean(a)
print("Mean : ",m)
n = st.median(a)
print('Median : ',n)

Mode :  10
Mean :  21.666666666666668
Median :  19.5


In [3]:
a = [20,10,50,10,21,90]
m = st.mean(a)
print("Mean : ",m)

Mean :  33.5


In [6]:
n = st.median(a)
print('Median : ',n)

Median :  20.5


In [7]:
import numpy as np
b = np.array([[10,20,30,50,10],[1,2,3,5,6]])
print(b)

[[10 20 30 50 10]
 [ 1  2  3  5  6]]


In [8]:
print("Dimension : ",b.ndim)

Dimension :  2


In [9]:
b= np.array([[10,20,30,50,10],[1,2,3,5,6],[1,1,1,1,1]])
print(b)

[[10 20 30 50 10]
 [ 1  2  3  5  6]
 [ 1  1  1  1  1]]


In [10]:
print(b)
print("Dimension : ",b.ndim)
print("Shape : ",b.shape)
print("Size : ",b.size)
print("Item size : ",b.itemsize)
print("Data type : ",b.dtype)

[[10 20 30 50 10]
 [ 1  2  3  5  6]
 [ 1  1  1  1  1]]
Dimension :  2
Shape :  (3, 5)
Size :  15
Item size :  4
Data type :  int32


In [12]:
c = np.empty((5,5))
d = np.arange(0,100,2)
print(d)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94
 96 98]


In [11]:
print(c)

[[6.23042070e-307 4.67296746e-307 1.69121096e-306 2.22520559e-306
  4.45058910e-308]
 [4.45059759e-308 1.20160575e-306 7.56587585e-307 1.37961302e-306
  1.05699242e-307]
 [8.01097889e-307 1.78020169e-306 7.56601165e-307 1.02359984e-306
  1.33510679e-306]
 [2.22522597e-306 1.33511018e-306 6.23057689e-307 1.02360120e-306
  8.45559303e-307]
 [1.00132483e-307 1.33511562e-306 8.90103560e-307 1.42410974e-306
  3.23796840e-317]]


In [13]:
e = np.reshape(d,(10,5))
f = np.reshape(e,(2,5,5))
print(f)

[[[ 0  2  4  6  8]
  [10 12 14 16 18]
  [20 22 24 26 28]
  [30 32 34 36 38]
  [40 42 44 46 48]]

 [[50 52 54 56 58]
  [60 62 64 66 68]
  [70 72 74 76 78]
  [80 82 84 86 88]
  [90 92 94 96 98]]]


In [14]:
print("Last element : ",d[10])
print("Element upto 10 : ",d[:10])
print("Last 5 element : ",d[-5:])
print("Alternate number : ",d[::2])

Last element :  20
Element upto 10 :  [ 0  2  4  6  8 10 12 14 16 18]
Last 5 element :  [90 92 94 96 98]
Alternate number :  [ 0  4  8 12 16 20 24 28 32 36 40 44 48 52 56 60 64 68 72 76 80 84 88 92
 96]


In [16]:
import pandas as pd


In [19]:
my_dict = {"Pid": [1,2,3,4,5],"Product id": [101,102,103,104,105],"Product Name": ['A','B','C','D','E'],"Price": [10,20,30,40,50],"Vendor": ['V1','V2','V3','V4','V5']}
res = pd.DataFrame(my_dict)
res

Pid  Product id Product Name  Price Vendor
0    1         101            A     10     V1
1    2         102            B     20     V2
2    3         103            C     30     V3
3    4         104            D     40     V4
4    5         105            E     50     V5